import React from 'react';
import type {
  Order,
  Lead,
  Project,
  Task,
  TeamMember,
  DiscountCode,
  LocalPaymentMethod,
} from '../types';
import {
  BaselineProjectIcon,
  PaperIndustryIcon,
  ToolProductionIcon,
  DesignSystemIcon,
  MockupIcon,
  LayoutIcon,
} from './icons';

export const dashboardProjects: Project[] = [
  {
    icon: <BaselineProjectIcon />,
    iconBgColor: 'bg-orange-100',
    title: 'Baseline Project',
    category: 'of user',
    description: 'Make something interesting and make your day more meaningful',
  },
  {
    icon: <PaperIndustryIcon />,
    iconBgColor: 'bg-green-100',
    title: 'Paper Industry',
    category: 'of user',
    description:
      'Paper industry to explain the industry that is explored and pursued',
  },
  {
    icon: <ToolProductionIcon />,
    iconBgColor: 'bg-blue-100',
    title: 'Tool Production',
    category: 'of user',
    description: 'Tools to provide your convenience in every access',
  },
];

export const dashboardTasks: Task[] = [
  {
    icon: <DesignSystemIcon />,
    iconBgColor: 'bg-indigo-100',
    title: 'Design System',
    description: 'Create design for new project',
  },
  {
    icon: <MockupIcon />,
    iconBgColor: 'bg-pink-100',
    title: 'Mockup Landing Page',
    description: 'Landing in new page',
  },
  {
    icon: <LayoutIcon />,
    iconBgColor: 'bg-amber-100',
    title: 'Layout',
    description: 'Make a new design layout',
  },
];

export const dashboardTeamMembers: TeamMember[] = [
  {
    avatarUrl: 'https://i.pravatar.cc/150?u=dhea',
    name: 'Dhea Mufni',
    role: 'Graphic Designer',
    status: 'online',
  },
  {
    avatarUrl: 'https://i.pravatar.cc/150?u=antonion',
    name: 'Antonion',
    role: 'Development',
    status: 'offline',
  },
];

export const digitalOrders: Order[] = [
  {
    id: 'ORD-D2401',
    date: '2025-08-10 09:12',
    cs: 'AN',
    customer: 'Budi Santoso',
    email: 'budi.s@email.com',
    phone: '081234567890',
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'QRIS',
    revenue: 150000,
    followupStage: 5,
    product: 'SaaS Pro Annual',
    transferProof: true,
    utm: 'google_ads',
  },
  {
    id: 'ORD-D2402',
    date: '2025-08-10 08:45',
    cs: 'BW',
    customer: 'Citra Lestari',
    email: 'citra.l@email.com',
    phone: '081222334455',
    status: 'Processing',
    paymentStatus: 'Unpaid',
    paymentMethod: 'VA Mandiri',
    revenue: 75000,
    followupStage: 1,
    product: 'SaaS Basic Monthly',
    transferProof: false,
    utm: 'facebook_cpc',
  },
  {
    id: 'ORD-D2403',
    date: '2025-08-11 10:00',
    cs: 'AN',
    customer: 'Agus Salim',
    email: 'agus.s@email.com',
    phone: '081987654321',
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'GoPay',
    revenue: 225000,
    followupStage: 5,
    product: 'Ultimate UI/UX Design Mastery Course',
    transferProof: true,
    utm: 'instagram_ads',
  },
  {
    id: 'ORD-D2404',
    date: '2025-08-12 14:20',
    cs: 'CS',
    customer: 'Rini Wulandari',
    email: 'rini.w@email.com',
    phone: '081298765432',
    status: 'Processing',
    paymentStatus: 'Paid',
    paymentMethod: 'BCA Transfer',
    revenue: 450000,
    followupStage: 3,
    product: 'Advanced Data Science Bootcamp',
    transferProof: true,
    utm: 'linkedin_outreach',
  },
  {
    id: 'ORD-D2405',
    date: '2025-08-13 11:05',
    cs: 'BW',
    customer: 'Siti Aminah',
    email: 'siti.a@email.com',
    phone: '081312345678',
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'OVO',
    revenue: 199000,
    followupStage: 5,
    product: 'Beginner Photography Course',
    transferProof: true,
    utm: 'tiktok_organic',
  },
  {
    id: 'ORD-D2406',
    date: '2025-08-14 09:30',
    cs: 'AN',
    customer: 'Farah Quinn',
    email: 'farah.q@email.com',
    phone: '081211223344',
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'BCA VA',
    revenue: 250000,
    followupStage: 5,
    product: 'Exclusive Cooking Masterclass',
    transferProof: true,
    utm: 'youtube_influencer',
  },
];
export const fisikOrders: Order[] = [
  {
    id: 'ORD-F5501',
    date: '2025-08-10 11:40',
    cs: 'AN',
    customer: 'Dewi Anggraini',
    email: 'dewi.a@email.com',
    phone: '081876543210',
    city: 'Jakarta',
    courier: 'JNE Express',
    status: 'Shipped',
    paymentStatus: 'Paid',
    paymentMethod: 'BCA Transfer',
    revenue: 250000,
    followupStage: 5,
    product: 'Hardware Kit v2',
    transferProof: true,
  },
  {
    id: 'ORD-F5502',
    date: '2025-08-09 14:00',
    cs: 'CS',
    customer: 'Rahmat Hidayat',
    email: 'rahmat.h@email.com',
    phone: '081765432109',
    city: 'Bandung',
    courier: 'SiCepat',
    status: 'Processing',
    paymentStatus: 'Unpaid',
    paymentMethod: 'COD',
    revenue: 180000,
    followupStage: 2,
    product: 'Starter Pack',
    transferProof: false,
  },
  {
    id: 'ORD-F5503',
    date: '2025-08-08 10:00',
    cs: 'BW',
    customer: 'Sari Puspita',
    email: 'sari.p@email.com',
    phone: '081234509876',
    city: 'Surabaya',
    courier: 'J&T',
    status: 'Return',
    paymentStatus: 'Paid',
    paymentMethod: 'QRIS',
    revenue: 350000,
    followupStage: 5,
    product: 'Premium Box',
    transferProof: true,
  },
];
export const lmsOrders: Order[] = [
  {
    id: 'ORD-LMS01',
    date: '2025-08-10 10:30',
    cs: 'DN',
    customer: 'Eka Wijaya',
    email: 'eka.w@email.com',
    phone: '081333444555',
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'Gopay',
    revenue: 99000,
    followupStage: 5,
    product: 'Course: Mastering CSS',
    transferProof: true,
    utm: 'instagram_story',
  },
  {
    id: 'ORD-LMS02',
    date: '2025-08-09 18:00',
    cs: 'AN',
    customer: 'Fitriani',
    email: 'fitri@email.com',
    phone: '081444555666',
    status: 'Processing',
    paymentStatus: 'Unpaid',
    paymentMethod: 'VA BNI',
    revenue: 125000,
    followupStage: 2,
    product: 'Course: Javascript for Beginners',
    transferProof: false,
    utm: 'google_cpc',
  },
];
export const leadOrders: Lead[] = [
  {
    id: 'LEAD-9101',
    date: '2025-08-10 15:00',
    cs: 'AN',
    customer: 'Indah Permata',
    email: 'indah.p@email.com',
    phone: '081654321098',
    followupStage: 1,
    fuEmailStage: 0,
    product: 'SaaS Enterprise',
    utm: 'linkedin',
  },
  {
    id: 'LEAD-9102',
    date: '2025-08-10 16:25',
    cs: 'CS',
    customer: 'Joko Susilo',
    email: 'joko.s@email.com',
    phone: '081543210987',
    followupStage: 0,
    fuEmailStage: 1,
    product: 'SaaS Pro Annual',
    utm: 'google_organic',
  },
];

export const initialDiscountCodes: DiscountCode[] = [
  {
    id: 'DC001',
    code: 'HEMAT20',
    type: 'percentage',
    value: 20,
    usageLimit: 100,
    timesUsed: 25,
    status: 'active',
    expiryDate: '2025-12-31',
  },
  {
    id: 'DC002',
    code: 'ONGKIRGRATIS',
    type: 'fixed',
    value: 15000,
    usageLimit: 50,
    timesUsed: 50,
    status: 'inactive',
    expiryDate: '2025-08-31',
  },
  {
    id: 'DC003',
    code: 'BELAJARASYIK',
    type: 'percentage',
    value: 50,
    usageLimit: 200,
    timesUsed: 150,
    status: 'active',
    expiryDate: '2025-09-30',
  },
];

export const initialLocalPaymentMethods: LocalPaymentMethod[] = [
  {
    id: 'PAY001',
    name: 'BCA Transfer',
    type: 'Bank Transfer',
    accountName: 'PT Dashyat Digital',
    accountNumber: '8881234567',
    status: 'active',
    logoUrl: 'https://i.ibb.co/L0f07S1/bca.png',
  },
  {
    id: 'PAY002',
    name: 'QRIS',
    type: 'QRIS',
    accountName: 'PT Dashyat Digital',
    accountNumber: 'N/A',
    status: 'active',
    qrImageUrl:
      'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Example',
  },
  {
    id: 'PAY003',
    name: 'GoPay',
    type: 'E-Wallet',
    accountName: 'Dashyat Store',
    accountNumber: '081234567890',
    status: 'active',
    logoUrl: 'https://i.ibb.co/fDbK4c7/gopay.png',
  },
  {
    id: 'PAY004',
    name: 'OVO',
    type: 'E-Wallet',
    accountName: 'Dashyat Store',
    accountNumber: '081234567890',
    status: 'inactive',
    logoUrl: 'https://i.ibb.co/b2Xn5sC/ovo.png',
  },
];

